name: schedule_workflow
on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'    
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
    - name: Executer le fichier Python
      run: |
        python script.py  
        
  test:
    needs: build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'    
        - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
      - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
        - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/random_number:v2